CC=gcc

libsyscalldemo : libsyscalldemo.o
	$(CC) -o libsyscalldemo libsyscalldemo.o

libsyscalldemo.o : libsyscalldemo.c
	$(CC) -c -o libsyscalldemo.o libsyscalldemo.c

clean :
	rm -f libsyscalldemo.o libsyscalldemo 	